config/routes.rb
Rails.application.routes.draw do
  get 'page/dashboard'

  get 'page/patient_dash'

  get 'page/cancel'

  get 'page/physician_dash'

  get 'page/patient_hist'

  get 'page/physician_app'

  get 'page/invoice'

  get 'page/admin_dash'

  get 'page/physician_admin'

  resources :appointments

  resources :slots

  resources :diagnostics

  resources :physicians

  resources :patients

    root 'page#dashboard'

end

app/models/slot.rb
class Slot < ActiveRecord::Base
	has_many :appointments
	has_many :physicians, through: :appointments
	has_many :patients, through: :appointments

	scope :avail, ->(s_name) { where("name != ?", s_name) }
	end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:name, :start_time.strftime('%I:%M:%S %p'), :end_time.strftime('%I:%M:%S %p'))
    end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_for(@slot) do |f| %>
  <% if @slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% @slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<h1>Listing slots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.name %></td>
        <td><%= slot.start_time.strftime('%I:%M:%S %p') %></td>
        <td><%= slot.end_time.strftime('%I:%M:%S %p') %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New slot</h1>

<%= render 'form' %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slot.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @slot.end_time %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>