config/routes.rb
Rails.application.routes.draw do
  get 'page/dashboard'

  get 'page/patient_dash'

  get 'page/cancel'

  get 'page/physician_dash'

  get 'page/patient_hist'

  get 'page/physician_app'

  get 'page/invoice'

  get 'page/admin_dash'

  get 'page/physician_admin'

  resources :appointments

  resources :slots

  resources :diagnostics

  resources :physicians

  resources :patients

    root 'page#dashboard'

end

app/models/physician.rb
class Physician < ActiveRecord::Base
	has_many :appointments
	has_many :slots, through: :appointments
	has_many :patients, through: :appointments
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
    @appointments = Appointment.all
    @slot = Slot.all
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end



  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name, :active)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<center>
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/physicians/edit.html.erb
<center><h1>Update Physician</h1>

<%= render 'form' %>


<%= link_to 'Back', physicians_path %>
</center>

app/views/physicians/index.html.erb
<center><h1>Select a Physician</h1></center>
<div class="CSSTableGenerator" >
<table>
  

  <tbody>
    <tr>
      <td>Name</td>
      <td>Availability</td>
    <% @physicians.each do |physician| %>
      <tr>
          <% if (physician.active == true) %>
          <td><%= physician.name %></td>
        <td><%= link_to 'Check Availability', physician %></td>
      </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/physicians/new.html.erb
<center>
<h1>Add New Physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>
</center>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p><center>
  <strong>Availability for 
  <%= @physician.name %> </strong>
</center>
</p>

		<% @reg = Array.new %>
		<% @slot.each do |arg| %>
			<% @reg.push arg.name %>
				<% end %>

		<% @today = Date.today %>
		<% @two_weeks = @today + 14 %>
		<% @open = Array.new %>
<center>
	<table>
		<% (@today..@two_weeks).each do |day| %>
		<tr>
  		<% if day.wday == 0 || day.wday == 6 %>
  			<% #nothing printed %>
  		<% else %>
  		<strong><%= day.strftime("%A, %b %d") %></strong>
		<div><%= link_to 'Schedule Appointment', new_appointment_path %></div>
		<% @reg.each do |tmp| %>
			<div><%= "#{tmp}" %></div>
		<% end %>
			<% @appointments.each do |appointment| %>
			<% if appointment.appointment_date == day and appointment.physician.id == @physician.id then %>
			<% @open.clear %>
			<% @open.push appointment.slot.name %>
			<% @open.uniq! %>
				<% @open.each do |tst| %>
					<div><H4><%= "The Following Appointment is unavailable: #{tst}" %></div></h4>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
</tr>

</table>
<%= link_to 'Schedule Appointment', new_appointment_path %>

<%= link_to 'Back', page_patient_dash_path %>
</center>