config/routes.rb
Rails.application.routes.draw do
  get 'page/dashboard'

  get 'page/patient_dash'

  get 'page/cancel'

  get 'page/physician_dash'

  get 'page/patient_hist'

  get 'page/physician_app'

  get 'page/invoice'

  get 'page/admin_dash'

  get 'page/physician_admin'

  resources :appointments

  resources :slots

  resources :diagnostics

  resources :physicians

  resources :patients

    root 'page#dashboard'

end

app/views/page/admin_dash.html.erb
<center><h1>Administrative Services</h1></center>
<center>
<p id ="navi" ><%= link_to 'New Patient', new_patient_path %></p>
<p id ="navi" ><%= link_to 'Invoice', page_invoice_path%> </p>                        
<p id ="navi" ><%= link_to 'Diagnostic Codes', diagnostics_path %></p>
<p id ="navi" ><%= link_to 'Physicians', page_physician_admin_path %></p>
<p id ="navi" ><%= link_to 'Physicians Report', page_physician_app_path %></p>
</center>

app/views/page/cancel.html.erb
<center><h1>Cancel an Appointment</h1></center>



<div class="CSSTableGenerator" >
<table>
  
    <tr>
      <td>Date</td>
      <td>Patient</td>
      <td>Physician</td>
      <td>Time</td>
      <td>Diagnosis</td>
      <td>Status</td>
      
    </tr>
  
      <% @current = Time.now%>
      <% @limit = Time.now.change(:hour => 8).strftime('%H:%M:%S') %>
      <% @curr_date = Date.today %>
 


 
    <% @appointments.each do |appointment| %>
      <tr>
        <% if appointment.appointment_date < @curr_date %>
          <% #Omits past appointments %>
        <% else %>
              <td><%= appointment.appointment_date.strftime("%A, %b %d") %></td>
              <td><%= appointment.patient.name %></td>
              <td><%= appointment.physician.name %></td>
              <td><%= appointment.slot.start_time.strftime('%I:%M:%S %p') %></td>
              <td><%= appointment.diagnostic.code %></td>
                <% if (@diff = appointment.slot.start_time.hour - @current.hour < 8 && appointment.appointment_date == @curr_date) %>
                    <td><strong><%= "Appointment Cannot be Cancelled" %></strong></td>
                 <% else %>
              <td><%= link_to 'Cancel Appointment', appointment, method: :delete, data: { confirm: 'Cancel Appointment?' } %></td>
              <% end %>
      <% end %>
      </tr>
      

  <% end %>
  
</table>
<%= link_to 'Back to Appointment Services', page_patient_dash_path %>
<br>

app/views/page/dashboard.html.erb
<body>
<center>
<div id ="home">
	
	<ul>
<li><%= link_to 'Appointment Services', page_patient_dash_path %></li>
<li><%= link_to 'Physicians Services', page_physician_dash_path %></li>
<li><%= link_to 'Administrative Services', page_admin_dash_path %></li>
</ul>
</center>
</body>

app/views/page/invoice.html.erb
<center><h1>Invoices</h1></center>

<div class="CSSTableGenerator" >
<table>
  
    <tr>
      <td>Date</td>
      <td>Notes</td>
      <td>Patient</td>
      <td>Physician</td>
      <td>Time</td>
      <td>Diagnosis</td>
      <th colspan="3"></td>
    </tr>
  

  
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.appointment_date.strftime("%A, %b %d") %></td>
        <td><%= appointment.note %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.slot.name %></td>
        <td><%= appointment.diagnostic.code %></td>
        <td><%= link_to 'Generate Invoice', appointment %></td>
        
        
        
      </tr>
    <% end %>
  
</table>

<br>

<%= link_to 'Back to Administrative Services', page_admin_dash_path %>

app/views/page/patient_dash.html.erb
<center><h1>Appointment Services</h1></center>
<center><p id ="navi" ><%= link_to 'Schedule an appointment', physicians_path %></p>
<p id ="navi" ><%= link_to 'Cancel an appointment', page_cancel_path%> </p> </center>                       

app/views/page/patient_hist.html.erb
<h1>Physician Reports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |app| %>
      <tr>
        <td><%= app.physician.name %></td>
        <td><%= app.appointment_date  %></td>
        <td><td><%= link_to 'Back', page_admin_dash_path %></td></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/page/physician_admin.html.erb
<center><h1>Update Physicians</h1>
<%= link_to 'New Physician', new_physician_path %></center>
<div class="CSSTableGenerator" >
<table>
  
    <tr>
      <td>Name</td>
      
     
      <td>Update</td>
    </tr>
  

  
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        
        
        <td><%= link_to 'Update', edit_physician_path(physician) %></td>
        
      </tr>
    <% end %>
  
</table>

<br>

app/views/page/physician_app.html.erb
<center><h1>Physician Reports</h1>
<%= link_to 'Back', page_admin_dash_path %></center>
<% @today = Date.today %>

<div class="CSSTableGenerator" >
<table>
    <tr>
    	<td>Physician</td>
    	<td>Appointment Date</td>
    	<td>Total Ammount</td>
    <% @appointments.each do |appointment| %>
    <% if appointment.appointment_date < @today %>
      <tr>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.appointment_date.strftime("%A, %b %d") %></td>
        <td><%= number_to_currency(appointment.diagnostic.cost) %></td>
               
      </tr>
    <% end %>
  <% end %> 
</table>

<br>

app/views/page/physician_dash.html.erb
<center><h1>Physician Servces</h1>

<p id ="navi"><%= link_to 'Appointments', appointments_path %></div>

</center>